### ISSUE TITLE
Cancel dust error

### ISSUE THREAD

**Issue by CryptoKong** [Codaone/DEXBot#620] opened 2019-06-18 20:37 UTC
Staggered orders worker error when attempting to cancel dust order:

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.6/site-packages/grapheneapi/api.py", line 168, in func
    r = func(*args, **kwargs)
  File "/home/cryptokong/.local/lib/python3.6/site-packages/grapheneapi/rpc.py", line 138, in method
    message = self.parse_response(r)
  File "/home/cryptokong/.local/lib/python3.6/site-packages/grapheneapi/rpc.py", line 106, in parse_response
    raise RPCError(ret["error"]["message"])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object 1.7.375389708

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cryptokong/.local/lib/python3.6/site-packages/dexbot-0.11.12-py3.6.egg/dexbot/strategies/staggered_orders.py", line 236, in maintain_strategy
    self.execute()
  File "/home/cryptokong/.local/lib/python3.6/site-packages/dexbot-0.11.12-py3.6.egg/dexbot/orderengines/bitshares_engine.py", line 479, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/home/cryptokong/.local/lib/python3.6/site-packages/graphenecommon/transactionbuilder.py", line 504, in broadcast
    raise e
  File "/home/cryptokong/.local/lib/python3.6/site-packages/graphenecommon/transactionbuilder.py", line 498, in broadcast
    ret, api="network_broadcast"
  File "/home/cryptokong/.local/lib/python3.6/site-packages/grapheneapi/api.py", line 176, in func
    self.post_process_exception(e)
  File "/home/cryptokong/.local/lib/python3.6/site-packages/bitsharesapi/bitsharesnoderpc.py", line 24, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object 1.7.375389708

![image](https://user-images.githubusercontent.com/33036236/59718069-3e5ea480-9211-11e9-8bc7-ebff42b97501.png)

## Specifications

  - Version: 0.11.12
  - OS: ubuntu 18.04

**Comment by bitfag** [comment] 2019-06-19 06:55
Duplicate of #587

**Closed by bitfag** 2019-06-19 06:55 UTC
Labels: [0] duplicate
