### ISSUE TITLE
Exception trx.ref_block_prefix == tapos_block_summary.block_id._hash[1]

### ISSUE THREAD

**Issue by PermieBTS** [Codaone/DEXBot#689] opened 2019-09-24 18:29 UTC
0.15.5 started causing exeptions.... lots of exeptions....  in case of internet connection errors bot is not able to resolve DNS after ic restores.... today hit new exeption in exeption ....
Im not sure maybe is that py3.7 case
2019-09- * INFO Canceling all orders
2019-09- * ERROR Unable to cancel order
Traceback (most recent call last):
  File "/home/styx/.local/lib/python3.7/site-packages/grapheneapi/api.py", line 168, in func
    r = func(*args, **kwargs)
  File "/home/styx/.local/lib/python3.7/site-packages/grapheneapi/rpc.py", line 138, in method
    message = self.parse_response(r)
  File "/home/styx/.local/lib/python3.7/site-packages/grapheneapi/rpc.py", line 106, in parse_response
    raise RPCError(ret["error"]["message"])
grapheneapi.exceptions.RPCError: Assert Exception: trx.ref_block_prefix == tapos_block_summary.block_id._hash[1]: 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/styx/.local/lib/python3.7/site-packages/dexbot-0.15.5-py3.7.egg/dexbot/orderengines/bitshares_engine.py", line 133, in _cancel_orders
    orders, account=self.account, fee_asset=self.fee_asset['id']
  File "/home/styx/.local/lib/python3.7/site-packages/dexbot-0.15.5-py3.7.egg/dexbot/orderengines/bitshares_engine.py", line 648, in retry_action
    return action(args, kwargs)
  File "/home/styx/.local/lib/python3.7/site-packages/bitshares/bitshares.py", line 956, in cancel
    return self.finalizeOp(op, account["name"], "active", kwargs)
  File "/home/styx/.local/lib/python3.7/site-packages/graphenecommon/chain.py", line 227, in finalizeOp
    return self.txbuffer.broadcast()
  File "/home/styx/.local/lib/python3.7/site-packages/graphenecommon/transactionbuilder.py", line 504, in broadcast
    raise e
  File "/home/styx/.local/lib/python3.7/site-packages/graphenecommon/transactionbuilder.py", line 498, in broadcast
    ret, api="network_broadcast"
  File "/home/styx/.local/lib/python3.7/site-packages/grapheneapi/api.py", line 176, in func
    self.post_process_exception(e)
  File "/home/styx/.local/lib/python3.7/site-packages/bitsharesapi/bitsharesnoderpc.py", line 24, in post_process_exception
    raise exceptions.UnhandledRPCError(msg)
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: trx.ref_block_prefix == tapos_block_summary.block_id._hash[1]:
2019-09-  INFO Orders canceled

**Comment by bitfag** [comment] 2019-09-26 16:29
Node issue, I can only suggest to add auto-reconnection to another node for that.

**Comment by vereten** [comment] 2019-09-30 14:48
> Node issue, I can only suggest to add auto-reconnection to another node for that.

I hit this issue, than deleted actual connected node, let dexbot reconnect, but problem persist. I do not think this is node issue.

**Comment by bitfag** [comment] 2020-03-11 19:11
Closing as duplicate of #680

**Closed by bitfag** 2020-03-11 19:11 UTC
Labels: [0] duplicate
