### ISSUE TITLE
Unexpected behaviour of Staggered Orders

### ISSUE THREAD

**Issue by lsji07** [Codaone/DEXBot#306] opened 2018-09-14 15:51 UTC
This is the defined approach to placing orders using staggered orders stategy.

_Approach from outside The bot starts filling in orders from the far ends, approaching the supposed center one order at a time, constantly switching sides. This should result in the user getting the best possible prices even if the center price is far from the supposed point. This also increases profits in the case when several orders are filled (either suddenly or when bot is off)._

On testing 1 side starts placing orders close to "spot" and the other is started from the high or low limit placed. In reality outside in orders should always be placed first before getting close to spot...

Major bug in my opinion as it can sell all of 1 asset.

Using win64 Version 0.6.2

**Comment by lsji07** [comment] 2018-09-14 15:52
@joelvai ?

**Comment by MarkoPaasila** [comment] 2018-09-17 07:42
Does "spot" mean "market center price" or "fair market value" or something else?

**Comment by MarkoPaasila** [comment] 2018-09-17 07:47
@lsji07 did the market have a clear center price or did you give it an initial center price? If the market has a huge spread, the bot assumes the center price is in the center, but it may not be the case. If the center price is given manually or the market has a clear center, many orders should not fill instantly - mostly a few if the price changes or isn't where expected. It is dangerous in an empty market together with wrong information. If you give it the correct center price and orders still fill, you can be happy as you have made profit.

**Comment by lsji07** [comment] 2018-09-19 10:31
> Does "spot" mean "market center price" or "fair market value" or something else?
Sorry, spot is an old trading term from the contract of buying or selling a commodity, security or currency for immediate settlement. Immediate used to be like 2 business days after the trade date. T+2. Now we are on T0. Thats where "Tzero" got their name from.

All trades carried out by the bot were in range. It never went out of the set range.

This is a timing issue really. To place orders over a wide range takes time. Say I want to market make on bridge.btc and bridge.rvn. Low bound could be 100 sats and as a long term strategy the high bound could be 0.1btc. (10-20 mins to reach the lower bound but the higher takes half a day potentially, Glad I'm not doing it manually!) Current market price is 240ish sats and was +/-10 sat spread to +/-2 sats.

When starting the bot places the outside orders first. But if the allow instant fill is ticked the bot places orders closer to spot/market price. When I did this the orders over spot filled and depleted the asset before the strategy orders were even close to being fully placed. Say a spread of 2% and 1% increments for example. The bot will continue to place orders until the high bound asset is severely depleted and the strategy set is not longer effective/possible. 

I did some trial and error to correct and found that the bot does correct the asset balances but I had to remove the "allow instant fill" tickbox and open the spread (to outside the market movements) until the strategy orders were placed and then reduce the spread to my preferred strategy.

I admit that my strategy is probably unusual but I would rather hold my RVN asset for a higher price later than set my strategy low and high bound lower and still market make currently.

**Comment by MarkoPaasila** [comment] 2018-09-20 05:38
Did you manually specify a "center price" different than the actual market center price? That would have caused such behavior.

> But if the allow instant fill is ticked the bot places orders closer to spot/market price

This sounds wierd. Did it not start from edges and approach center? Did it just place orders close to center?

**Comment by lsji07** [comment] 2018-09-20 10:27
> Did you manually specify a "center price" different than the actual market center price? That would have caused such behavior.
> 
> > But if the allow instant fill is ticked the bot places orders closer to spot/market price
> 
> This sounds wierd. Did it not start from edges and approach center? Did it just place orders close to center?

No. I used the bots market center price.

With instant fill ticked it placed 1 no order above market center price. This was configured to match the final strategies spread but with a tight spread it caused the orders to fill instantly selling most of 1 asset in the pair.

**Comment by MarkoPaasila** [comment] 2018-09-20 11:44
Sorry about questioning, but I think accurate understanding will help us fix the problem. Please word your answers carefully. I don't fully understand this:

> it placed 1 no order above market center price

- did it place no order above market center price, or
- did it place one order right above market center price, or
- did it place one order *at* center price, or
- did it place one order close to upper bound?
- did it place one buy order above market center price, or
- something else?

Also, did it approach center by placing furthest orders first, and then one closer each time, until it reached market center price? When the order filled, was did it start to remove furthest orders and place a new order at mcp - which immediately filled again?

**Comment by MarkoPaasila** [comment] 2018-10-30 11:07
Does someone else understand what the issue is here. I'm too stupid.

**Comment by bitfag** [comment] 2018-11-04 18:53
Probably it's better to discuss strategy logic in telegram channel first and then fill a bug whether there is really a bug. It's unclear to me what @lsji07 tries to explain.

**Comment by MarkoPaasila** [comment] 2018-11-05 21:00
I'll close this. If this really is an issue we will certainly bump into it later.

**Closed by MarkoPaasila** 2018-11-05 21:00 UTC
Labels: Priority: Low, Status: Requires Discussion, Type: Question
