### ISSUE TITLE
WalletLocked() error on worker creation

### ISSUE THREAD

**Issue by Eltryou** [Codaone/DEXBot#375] opened 2018-10-30 23:47 UTC
## Expected Behavior

Dexbot first run ask for encryption password and confirmation, then keep track for next launchs

## Actual Behavior

Using last build (DEXBot-gui-win64-0.7.18.zip) on a fresh new windows7 vmware, app run, ask dexbot encryption password and confirmation then when adding and validating a worker, give error msg:
WalletLocket() and this tracelog
Traceback (most recent call last):
  File "dexbot\views\errors.py", line 95, in func_wrapper
  File "dexbot\controllers\worker_controller.py", line 244, in handle_save
  File "dexbot\controllers\worker_controller.py", line 59, in add_private_key
  File "site-packages\bitshares-0.2.0-py3.5.egg\bitshares\wallet.py", line 161, in addPrivateKey
  File "site-packages\graphenelib-1.0.1-py3.5.egg\graphenestorage\base.py", line 136, in add
  File "site-packages\graphenelib-1.0.1-py3.5.egg\graphenestorage\masterpassword.py", line 185, in encrypt
graphenestorage.exceptions.WalletLocked

If i restart dexbot, it didnt record the first encryption password choosen and ask again for a password and confirmation 

## Steps to Reproduce the Problem

  1.Launch dexbot (DEXBot-gui-win64-0.7.18.zip) on a system with no past dexbot account
  2.Choose password, then try to validate a new worker to get walletlocked() error
  3.Relaunch dexbot, it ask again for account creation password

## Specifications

  - Version:0.7.18
  - OS:win7x64

**Comment by joelvai** [comment] 2018-10-31 06:40
I was able to reproduce this, I will start working on fixing the problem now.

**Comment by Eltryou** [comment] 2018-10-31 09:49
same behavior on a fresh ubuntu 16.04 vmware using published build or building from source 0.7.18

**Comment by joelvai** [comment] 2018-10-31 10:01
Problem is caused by the latest bitshares 0.2.0 dependency update, which broke how the Wallet is used. This also causes a problem, which doesn't let you create the Wallet at all. I am looking a way to fix this. For now if you have already created workers they should be fine, but adding new private keys does not work as well as new wallets. I recommend using older version (0.7.9) of DEXBot for creating workers.

**Comment by joelvai** [comment] 2018-10-31 11:55
@Eltryou as an update to this issue, I am currently waiting for an update to python-bitshares dependency where we discovered the origin of the issue.

**Comment by joelvai** [comment] 2018-10-31 14:03
This is fixed in the latest release 0.7.19.

**Closed by joelvai** 2018-10-31 14:03 UTC
Labels: Priority: High, Status: In Progress, Type: Bug
