### ISSUE TITLE
Assertion Errors when creating any worker

### ISSUE THREAD

**Issue by murderistic** [Codaone/DEXBot#267] opened 2018-08-06 15:47 UTC
## Expected Behavior
Create worker profile to enable trading.

## Actual Behavior
Still getting assertion errors whenever creating a new worker (or any worker). Newest version of today:

Traceback (most recent call last):
  File "dexbot\views\errors.py", line 95, in func_wrapper
  File "dexbot\controllers\worker_controller.py", line 207, in validate_form
  File "dexbot\controllers\worker_controller.py", line 152, in validate_private_key
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitsharesbase\account.py", line 151, in init
  File "lib\site-packages\graphenebase\account.py", line 362, in init
  File "lib\site-packages\graphenebase\base58.py", line 52, in init
  File "lib\site-packages\graphenebase\base58.py", line 181, in base58CheckDecode
AssertionError

## Steps to Reproduce the Problem

  1. Start Dexbot
  2. Create worker
  3. Click Save

## Specifications

  - Version:  0.5.10
  - OS: Win 10 Latest updates

**Comment by MarkoPaasila** [comment] 2018-08-07 08:26
Usually that can be fixed by reinstalling/upgrading cryptograpny with pip. But this can't be done with the package version.

**Comment by MarkoPaasila** [comment] 2018-10-18 07:47
@murderistic have you had success with later versions?

**Comment by joelvai** [comment] 2018-10-25 07:40
Closing this issue since can't be reproduced anymore on DEXBot 0.7.9. If this bug reoccurs please open new ticket.

**Closed by joelvai** 2018-10-25 07:40 UTC
Labels: Priority: Medium, Status: Available, Type: Bug
