### ISSUE TITLE
ERROR - in onMarketUpdate() TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by grctest** [Codaone/DEXBot#157] opened 2018-05-30 18:10 UTC
## Expected Behavior

Start USD worker, Stop CNY worker, Start CNY worker.

## Actual Behavior

Start USD worker, Stop CNY worker & cause USD worker to fail, Start CNY worker successfully.

## Steps to Reproduce the Problem

  1. Run CNY worker. Start USD worker.
  2. Stop CNY worker - causing error.
  3. Start CNY worker - CNY continues whilst USD disabled.

## Specifications

  - Version: 0.2.3
  - OS: Xubuntu

---

## Debug logs:

```
2018-05-30 18:29:45,582 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Orders correct on market
2018-05-30 18:30:03,450 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Canceling all orders
2018-05-30 18:30:03,621 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - ERROR - in onMarketUpdate()
Traceback (most recent call last):
  File "dexbot/worker.py", line 139, in on_market
  File "site-packages/Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
  File "dexbot/strategies/relative_orders.py", line 126, in check_orders
  File "dexbot/basestrategy.py", line 210, in get_order
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/price.py", line 448, in __init__
TypeError: list indices must be integers or slices, not str
2018-05-30 18:30:03,623 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Canceling all orders
2018-05-30 18:30:06,514 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Orders canceled
2018-05-30 18:30:10,136 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
......
[SHORTENED - REPEATING!]
......
2018-05-30 18:30:12,904 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:30:28,495 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Initializing Relative Orders
2018-05-30 18:30:28,601 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Change detected, updating orders
2018-05-30 18:30:28,765 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Canceling all orders
2018-05-30 18:30:28,855 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Orders canceled
2018-05-30 18:30:28,991 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Placing a buy order for 1.1235 CNY @ 1.12350459
2018-05-30 18:30:34,007 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Placing a sell order for 1.0 BTS @ 1.17967982
```

**Comment by MarkoPaasila** [comment] 2018-10-18 07:44
@grctest can you also confirm if this is solved?

**Comment by joelvai** [comment] 2018-10-30 13:15
Closing this since haven't been able to reproduce with newest version. Please open again if reoccurs.

**Closed by joelvai** 2018-10-30 13:15 UTC
Labels: Status: Available, Type: Bug
