### ISSUE TITLE
No new order can be submitted after the order is filled

### ISSUE THREAD

**Issue by hiquanta** [Codaone/DEXBot#105] opened 2018-04-30 02:47 UTC
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shes/.local/lib/python3.5/site-packages/bitshares-0.1.14-py3.5.egg/bitsharesapi/bitsharesnoderpc.py", line 54, in rpcexec
    return self.rpc.rpcexec(self, payload)
  File "/home/shes/.local/lib/python3.5/site-packages/graphenelib-0.6.1-py3.5.egg/grapheneapi/graphenewsrpc.py", line 173, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object

**Comment by mikakoi** [comment] 2018-05-02 06:28
This is a duplicate of #96 closing.

**Closed by mikakoi** 2018-05-02 06:28 UTC
