### ISSUE TITLE
This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent WIndows (10.0.10586 or above)

### ISSUE THREAD

**Issue by appelpaiter** [Codaone/DEXBot#549] opened 2019-04-11 11:27 UTC
## Expected Behavior
Regular startup, no problems.
No errors till version DEXbot-gui-win-64-0.9.5

## Actual Behavior
See title of issue and added screenshot.

## Steps to Reproduce the Problem
![error](https://user-images.githubusercontent.com/49520258/55953823-6fdd5180-5c5d-11e9-86c4-d6dc58c0f87a.png)

  1.Started the bot couple of times, also version 0.10.0. No positive results.
  2.
  3.

## Specifications
Hi guys. I know the error asks me to update my windows. Unfortunately it's not possible on this machine. Please support :) Thanks in advance.
  - Version:DEXbot-gui-win-64-0.9.5
  - OS:
![error](https://user-images.githubusercontent.com/49520258/55953391-44a63280-5c5c-11e9-8863-321dfddbf2f4.png)

**Comment by dominic22** [comment] 2019-04-11 23:29
The version of pyqt5 was updated in https://github.com/Codaone/DEXBot/pull/414

It seems this is the cause of the problem as you can see here:
https://github.com/winpython/winpython/issues/592

PyQt5.Qt imports a lot of modules including bluetooth which seems to has issues on Win8.1.

I think we can solve the issue according to the suggestion of altendky:
https://github.com/winpython/winpython/issues/592#issuecomment-408290186
Also see here:
https://github.com/spyder-ide/qtpy/issues/166

So it looks like the imports have to be edited to support versions below Windows 10.

**Comment by joelvai** [comment] 2019-04-23 07:08
Fix for this issue is merged on `devel` branch and is going to be included in the next release.

**Closed by joelvai** 2019-04-23 07:08 UTC
