### ISSUE TITLE
ERROR - in onMarketUpdate() KeyError: 'sell_price'

### ISSUE THREAD

**Issue by grctest** [Codaone/DEXBot#156] opened 2018-05-30 18:07 UTC
## Expected Behavior

Starting up multiple relative order bot workers works.

## Actual Behavior

Started my USD:BTS relative order bot, it ran fine. I then started my CNY:BTS relative order bot & this error occurred, causing the USD:BTS worker to become disabled.

## Steps to Reproduce the Problem

  1. Start USD:BTS bot.
  2. Start CNY:BTS bot.
  3. Experience error.

## Specifications

  - Version: 0.2.3
  - OS: Xubuntu

---

## Debug logs

```
2018-05-30 18:56:40,501 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Canceling all orders
2018-05-30 18:56:43,191 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Orders canceled
2018-05-30 18:57:02,999 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Initializing Relative Orders
2018-05-30 18:57:03,099 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Change detected, updating orders
2018-05-30 18:57:03,816 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Canceling all orders
2018-05-30 18:57:03,904 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Orders canceled
2018-05-30 18:57:03,951 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Placing a buy order for 5.44646 BTS @ 5.4464611
2018-05-30 18:57:09,037 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Placing a sell order for 1.0 USD @ 5.99110721
2018-05-30 18:57:15,349 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Done placing orders
2018-05-30 18:57:18,530 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Initializing Relative Orders
2018-05-30 18:57:18,621 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Change detected, updating orders
2018-05-30 18:57:18,776 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Canceling all orders
2018-05-30 18:57:18,900 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Orders canceled
2018-05-30 18:57:18,992 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Placing a buy order for 1.1417 CNY @ 1.14172898
2018-05-30 18:57:24,544 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Placing a sell order for 1.0 BTS @ 1.19881543
2018-05-30 18:57:29,748 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Done placing orders
2018-05-30 18:57:30,400 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - ERROR - in onMarketUpdate()
Traceback (most recent call last):
  File "dexbot/worker.py", line 139, in on_market
  File "site-packages/Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
  File "dexbot/strategies/relative_orders.py", line 125, in check_orders
  File "dexbot/basestrategy.py", line 210, in get_order
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/price.py", line 448, in __init__
KeyError: 'sell_price'
2018-05-30 18:57:30,403 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Canceling all orders
2018-05-30 18:57:32,747 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Orders canceled
2018-05-30 18:57:35,871 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:35,962 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,051 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,137 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,224 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,315 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,417 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,512 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,600 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,643 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,735 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
2018-05-30 18:57:36,821 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Worker "BTS USD Liquidity" is disabled
```

**Comment by grctest** [comment] 2018-05-31 21:07
Upgraded to the newest version, experienced this error again.

Debug logs:
```
2018-05-31 21:36:09,244 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Orders correct on market
2018-05-31 21:36:12,026 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Orders correct on market
2018-05-31 21:36:13,698 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Initializing Relative Orders
2018-05-31 21:36:13,797 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Change detected, updating orders
2018-05-31 21:36:13,900 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Canceling all orders
2018-05-31 21:36:13,994 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Orders canceled
2018-05-31 21:36:14,315 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a buy order for 40.96915 BTS @ 8.19383173
2018-05-31 21:36:17,919 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a sell order for 5.0 HERTZ @ 8.39867752
2018-05-31 21:36:20,882 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Done placing orders
2018-05-31 21:36:20,889 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Change detected, updating orders
2018-05-31 21:36:21,004 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Canceling all orders
2018-05-31 21:36:22,612 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Orders canceled
2018-05-31 21:36:22,665 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a buy order for 34.27455 BTS @ 6.85491118
2018-05-31 21:36:30,580 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a sell order for 5.0 HERTZ @ 7.02628396
2018-05-31 21:36:32,845 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Done placing orders
2018-05-31 21:36:32,852 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Change detected, updating orders
2018-05-31 21:36:32,955 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Canceling all orders
2018-05-31 21:36:34,405 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Orders canceled
2018-05-31 21:36:34,456 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a buy order for 31.34939 BTS @ 6.26987967
2018-05-31 21:36:39,881 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a sell order for 5.0 HERTZ @ 6.42662666
2018-05-31 21:36:45,546 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Done placing orders
2018-05-31 21:36:46,098 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - ERROR - in onMarketUpdate()
Traceback (most recent call last):
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/worker.py", line 139, in on_market
    self.workers[worker_name].onMarketUpdate(data)
  File "/home/dexbot/.local/lib/python3.6/site-packages/Events-0.3-py3.6.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/strategies/relative_orders.py", line 125, in check_orders
    current_sell_order = self.get_order(stored_sell_order)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/basestrategy.py", line 210, in get_order
    order = Order(order_id)
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/price.py", line 448, in __init__
    super(Order, self).__init__(order["sell_price"])
KeyError: 'sell_price'
2018-05-31 21:36:46,100 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Canceling all orders
2018-05-31 21:36:47,630 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Orders canceled
2018-05-31 21:36:51,107 - CNY BTS PLUS using account aba-dexbot-plus on BTS/CNY - INFO - Worker "CNY BTS PLUS" is disabled
```

**Comment by MarkoPaasila** [comment] 2018-10-18 07:39
@grctest this shouldn't be an issue any more. Can you confirm?

**Comment by MarkoPaasila** [comment] 2018-10-24 09:44
I think here's still something to try to reproduce. Someone also reported Staggered Orders to halt (reset?) when Relative Orders was started.

**Comment by joelvai** [comment] 2018-10-30 13:15
Closing this since haven't been able to reproduce with newest version. Please open again if reoccurs.

**Closed by joelvai** 2018-10-30 13:15 UTC
Labels: Priority: Medium, Status: Available, Type: Bug
