### ISSUE TITLE
Multiple Workers per Account *Any Asset*

### ISSUE THREAD

**Issue by DunnCreativeSS** [Codaone/DEXBot#513] opened 2019-03-18 17:14 UTC
Multiple Workers per Account *Any Asset*

**Comment by DunnCreativeSS** [comment] 2019-03-18 17:14
https://github.com/Codaone/DEXBot/pull/514

**Comment by bitfag** [comment] 2019-03-18 17:20
Duplicate of #434

**Comment by thehapax** [comment] 2019-03-18 20:37
closing duplicate as per request by @PermieBTS

**Closed by thehapax** 2019-03-18 20:37 UTC
Labels: [0] duplicate
