### ISSUE TITLE
ERROR - Worker initialisation. TypeError: 'NoneType' object is not subscriptable. ValueError: Cannot interpret lists! Please load elements individually!

### ISSUE THREAD

**Issue by grctest** [Codaone/DEXBot#158] opened 2018-05-30 18:17 UTC
## Expected Behavior

Start/Stop USD worker.

## Actual Behavior

Experienced glitch which required closing the dexbot.

## Steps to Reproduce the Problem

  1. Stop USD worker.
  2. Start USD worker.

## Specifications

  - Version: 0.2.3
  - OS: Xubuntu

## Debug logs:

```
2018-05-30 18:33:53,138 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Canceling all orders
2018-05-30 18:33:53,230 - BTS USD Liquidity using account aba-dexbot-usd on USD/BTS - INFO - Orders canceled
 
2018-05-30 18:34:01,509 - BTS USD Liquidity using account aba-dexbot-usd on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "dexbot/worker.py", line 75, in init_workers
  File "dexbot/strategies/relative_orders.py", line 12, in __init__
  File "dexbot/basestrategy.py", line 116, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/account.py", line 44, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 107, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/account.py", line 61, in refresh
TypeError: 'NoneType' object is not subscriptable
 
Traceback (most recent call last):
  File "dexbot/views/errors.py", line 50, in func_wrapper
  File "dexbot/views/worker_item.py", line 60, in start_worker
  File "dexbot/controllers/main_controller.py", line 40, in create_worker
  File "dexbot/worker.py", line 170, in add_worker
  File "dexbot/worker.py", line 93, in update_notify
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/notify.py", line 118, in reset_subscriptions
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/notify.py", line 107, in get_market_ids
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/market.py", line 50, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/asset.py", line 33, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 107, in __init__
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/asset.py", line 41, in refresh
  File "site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 82, in __init__
ValueError: Cannot interpret lists! Please load elements individually!
```

**Comment by grctest** [comment] 2018-05-31 21:10
Another occurrence whilst using the latest version 0.2.5:

```
2018-05-31 21:32:19,364 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Orders canceled
2018-05-31 21:32:19,816 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a buy order for 40.96915 BTS @ 8.19383173
2018-05-31 21:32:23,968 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a sell order for 5.0 HERTZ @ 8.39867752
2018-05-31 21:32:27,588 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Done placing orders
2018-05-31 21:32:27,594 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Change detected, updating orders
2018-05-31 21:32:27,692 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Canceling all orders
2018-05-31 21:32:29,126 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Orders canceled
2018-05-31 21:32:29,175 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a buy order for 34.27455 BTS @ 6.85491118
2018-05-31 21:32:33,463 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Placing a sell order for 5.0 HERTZ @ 7.02628396
2018-05-31 21:32:35,709 - HERTZ Liquidity bot using account aba-dexbot on HERTZ/BTS - INFO - Done placing orders
2018-05-31 21:32:36,156 - CNY BTS PLUS using account aba-dexbot-plus on unknown - ERROR - Worker initialisation
Traceback (most recent call last):
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/worker.py", line 75, in init_workers
    view=self.view
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/strategies/relative_orders.py", line 12, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/basestrategy.py", line 116, in __init__
    bitshares_instance=self.bitshares
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/account.py", line 44, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 107, in __init__
    self.refresh()
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/account.py", line 61, in refresh
    [account["id"]], False)[0][1]
KeyError: 1


Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/worker.py", line 174, in run
    self.update_notify()
  File "/home/dexbot/.local/lib/python3.6/site-packages/dexbot-0.2.6-py3.6.egg/dexbot/worker.py", line 102, in update_notify
    bitshares_instance=self.bitshares
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/notify.py", line 91, in __init__
    markets=self.get_market_ids(markets),
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/notify.py", line 107, in get_market_ids
    blockchain_instance=self.blockchain
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/market.py", line 50, in __init__
    quote = Asset(quote_symbol, blockchain_instance=self.blockchain)
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/asset.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 107, in __init__
    self.refresh()
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/asset.py", line 41, in refresh
    super(Asset, self).__init__(asset, blockchain_instance=self.blockchain)
  File "/home/dexbot/.local/lib/python3.6/site-packages/bitshares-0.1.16-py3.6.egg/bitshares/blockchainobject.py", line 82, in __init__
    "Cannot interpret lists! Please load elements individually!")
ValueError: Cannot interpret lists! Please load elements individually!
```

**Comment by Netzarim** [comment] 2018-08-04 05:32
Windows too, version 5.6:

Traceback (most recent call last):
  File "lib\site-packages\grapheneapi\api.py", line 137, in func
  File "lib\site-packages\grapheneapi\rpc.py", line 93, in method
  File "lib\site-packages\grapheneapi\rpc.py", line 63, in parse_response
grapheneapi.exceptions.RPCError: Bad Cast: Invalid cast from type 'object_type' to Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 61, in __init__
  File "dexbot\strategies\relative_orders.py", line 150, in check_orders
  File "dexbot\strategies\relative_orders.py", line 125, in update_orders
  File "dexbot\basestrategy.py", line 457, in market_buy
  File "dexbot\basestrategy.py", line 602, in retry_action
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\bitshares.py", line 274, in finalizeOp
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 325, in sign
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitshares\transactionbuilder.py", line 301, in constructTx
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitsharesbase\transactions.py", line 26, in addRequiredFees
  File "lib\site-packages\grapheneapi\api.py", line 145, in func
  File "lib\site-packages\bitshares-0.1.19-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 19, in post_process_exception
bitsharesapi.exceptions.UnhandledRPCError: Bad Cast: Invalid cast from type 'object_type' to Object

**Comment by mikakoi** [comment] 2018-08-06 04:57
@Netzarim That is a different traceback not related to this issue.

**Comment by MarkoPaasila** [comment] 2018-10-18 07:45
@grctest this shouldn't be an issue any more either. Can you please confirm?

**Comment by MarkoPaasila** [comment] 2018-10-24 09:53
Somehow I have the feeling that Nonetype objects are related to poor node connections. I might be wrong. Could it be related to stop/start worker or modify worker? Why do we expect there to be an object where there is none?

**Comment by joelvai** [comment] 2018-10-30 13:15
Closing this since haven't been able to reproduce with newest version. Please open again if reoccurs.

**Closed by joelvai** 2018-10-30 13:15 UTC
Labels: Priority: Medium, Status: Available, Type: Bug
