### ISSUE TITLE
grapheneapi.exceptions.RPCError: Execution error

### ISSUE THREAD

**Issue by dasvayda** [Codaone/DEXBot#695] opened 2019-10-24 10:53 UTC
I often get this error.

> Traceback (most recent call last):
>   File "site-packages\grapheneapi\api.py", line 168, in func
>   File "site-packages\grapheneapi\rpc.py", line 138, in method
>   File "site-packages\grapheneapi\rpc.py", line 106, in parse_response
> grapheneapi.exceptions.RPCError: Execution error

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "dexbot\strategies\staggered_orders.py", line 612, in replace_virtual_order_with_real
>   File "dexbot\orderengines\bitshares_engine.py", line 565, in place_market_buy_order
>   File "dexbot\orderengines\bitshares_engine.py", line 648, in retry_action
>   File "site-packages\bitshares\market.py", line 506, in buy
>   File "site-packages\graphenecommon\chain.py", line 227, in finalizeOp
>   File "site-packages\graphenecommon\transactionbuilder.py", line 504, in broadcast
>   File "site-packages\graphenecommon\transactionbuilder.py", line 498, in broadcast
>   File "site-packages\grapheneapi\api.py", line 176, in func
>   File "site-packages\bitsharesapi\bitsharesnoderpc.py", line 24, in post_process_exception
> bitsharesapi.exceptions.UnhandledRPCError: Execution error

**Comment by PermieBTS** [comment] 2019-10-28 10:16
It's a node error, have you tried sorting the node list in settings to try different nodes?

**Comment by bitfag** [comment] 2020-03-11 18:57
duplicate of #692

**Closed by bitfag** 2020-03-11 18:57 UTC
Labels: [0] duplicate
