### ISSUE TITLE
[Windows] Unable to find Object

### ISSUE THREAD

**Issue by hubba1** [Codaone/DEXBot#246] opened 2018-07-23 01:07 UTC
## Expected Behavior
expected this bot to start like the other two I"m running

## Actual Behavior - (this is the error message I'm getting)
Traceback (most recent call last):
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 54, in rpcexec
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 173, in rpcexec
grapheneapi.exceptions.RPCError: Assert Exception: maybe_found != nullptr: Unable to find Object 1.7.128987006

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dexbot\worker.py", line 76, in init_workers
  File "dexbot\strategies\relative_orders.py", line 60, in __init__
  File "dexbot\strategies\relative_orders.py", line 149, in check_orders
  File "dexbot\strategies\relative_orders.py", line 124, in update_orders
  File "dexbot\basestrategy.py", line 436, in market_buy
  File "dexbot\basestrategy.py", line 580, in retry_action
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\market.py", line 432, in buy
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\bitshares.py", line 282, in finalizeOp
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 388, in broadcast
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitshares\transactionbuilder.py", line 382, in broadcast
  File "lib\site-packages\graphenelib-0.6.1-py3.5.egg\grapheneapi\graphenewsrpc.py", line 213, in method
  File "lib\site-packages\bitshares-0.1.16-py3.5.egg\bitsharesapi\bitsharesnoderpc.py", line 66, in rpcexec
bitsharesapi.exceptions.UnhandledRPCError: Assert Exception: maybe_found != nullptr: Unable to find Object 1.7.128987006

## Steps to Reproduce the Problem

  1.??
  2.?
  3.?

## Specifications

  - Version:0.4.8
  - OS:win10

**Comment by MarkoPaasila** [comment] 2018-07-24 10:49
@mikakoi Windows users are getting all these errors. When building the next release can you take some time to test it on Windows?

**Comment by lsji07** [comment] 2018-07-26 12:46
I have seen this error before. Usually it's when a strategy is started and worker is stopped before the entire strategy is completed. A few orders or one is traded on the dex but the bot/worker doesn't detect the trade and throws up the above error. The only fix I have found is to clear the worker. Clear the orders placed onto the dex on the workers account manually and start the strategy from a clean slate and not interrupt it until complete.

**Comment by mikakoi** [comment] 2018-08-06 09:26
Adding a "small" amount of delay isn't exactly a fix for this, we can't possibly know how long we need to wait. We need a better fix for this.

**Comment by bitfag** [comment] 2018-08-06 10:01
What about Try/Except with X retries?

**Comment by mikakoi** [comment] 2018-08-06 10:09
The market_buy already uses the retry_action method which does x retries with try/except, so it wouldn't be hard to implement. 
The problem is that we don't exactly know what has happened to the order, the order might or might not be in the blockchain. I would like to test this but I've never encountered this error :|

**Comment by MarkoPaasila** [comment] 2018-08-06 10:28
@mikakoi you need to use a poor node, which shouldn't be too hard to find LOL

**Comment by MarkoPaasila** [comment] 2018-08-06 10:37
1. Do we get a specific return value if an order placement *doesn't* succeed?
2. This exception shouldn't be cared about if we are cancelling orders. We can just assume it has been successfully canceled or filled if we get the error, and then proceed as usual with the strategy.
3. If we don't get any indication that an order has *not* succeeded, but then get this error, we need to retry placing the order.

**Comment by bitfag** [comment] 2018-08-06 11:54
@mikakoi "Unable to find Object" is a temporary error, order should only be "exists"
 or appear as "deleted order 1.2.3". So implementing several retries inside `get_order()` should be the easiest solution.

**Comment by bitfag** [comment] 2018-08-07 08:28
@MarkoPaasila, exactly.

**Comment by MarkoPaasila** [comment] 2018-10-24 09:56
I haven't seen this error message for a long time, nor have I heard of one. @mikakoi do you remember if this was finished, or has it been fixed in connection with some other bug?

**Comment by mikakoi** [comment] 2018-10-26 11:09
I don't think there was a fix made for this, but I've never personally encountered this bug.

**Comment by MarkoPaasila** [comment] 2018-10-30 13:07
I'll take the courage to close.

**Closed by MarkoPaasila** 2018-10-30 13:07 UTC
Labels: Priority: Medium, Status: Available, Type: Bug
