### ISSUE TITLE
Gui hits a (not responding) and doenst recover

### ISSUE THREAD

**Issue by RobJah** [Codaone/DEXBot#506] opened 2019-03-05 17:16 UTC
This issue surfaced after the latest upgrade. Every day since the upgrade my dexbot gui completely freezes with no chance of recovering, no buttons respond which only leave the option to terminated it by force. 

## Expected Behavior
like ever before:
1 start dexbot gui;
2 turn on workers with some time in between to make sure the software can compute;
3 keep gui running for weeks without turning anything off.

## Actual Behavior
1 start dexbot gui;
2 turn on workers with some time in between to make sure the software can compute;
3 Whenever more than 1 worker encounters a market move of more than 1 filled order the whole gui freezes (50% of the time atleast). 

## Steps to Reproduce the Problem

  1. Maybe run 10 workers like i do on BTS markets > so when BTS makes a move, all the workers make a move.
  2.
  3.

## Specifications

  - Version: 0.9.19
  - OS: Windows 10
  -connection is great, low ping, fast laptop

## What the DEXbot-gui prompt window shows me:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "site-packages\bitsharesapi\websocket.py", line 216, in _ping
  File "site-packages\bitsharesapi\websocket.py", line 388, in method
  File "site-packages\bitsharesapi\websocket.py", line 354, in rpcexec
  File "site-packages\websocket\_app.py", line 153, in send
  File "site-packages\websocket\_core.py", line 250, in send
  File "site-packages\websocket\_core.py", line 275, in send_frame
  File "site-packages\websocket\_core.py", line 445, in _send
  File "site-packages\websocket\_socket.py", line 117, in send
  File "ssl.py", line 944, in send
  File "ssl.py", line 642, in write
ConnectionResetError: [WinError 10054] De externe host heeft een verbinding verbroken

Good luck, wizzards!

**Comment by joelvai** [comment] 2019-03-06 06:49
This problem is caused by bug in the Bitshares Core [issue #1620](https://github.com/bitshares/bitshares-core/issues/1620). I can take a look to fix this by updating the pybitshares to version 0.3.0.

**Comment by RobJah** [comment] 2019-03-07 07:13
Hi

I have reverted back to the previous version, which now gives me the same trouble. 
Not as frequent as the latest version, but still there are total freezes non the less.

**Comment by thehapax** [comment] 2019-03-18 20:37
@RobJah is this still an issue with the latest release? if not we'd like to close this issue. thanks.

**Comment by RobJah** [comment] 2019-03-18 21:13
Yes it only is an issue with the latest release (0.9.19) so im using 0.9.5 now.
I didnt try anything after joelvai said he knows what resolves the problem.

**Comment by thehapax** [comment] 2019-03-20 00:43
@RobJah in the next day there will be a newer release 0.10.1 once it comes out, please give it a try and see if you still have problems. thanks

**Comment by joelvai** [comment] 2019-03-20 07:49
The release ended up being 0.10.0, but let me know if this problem still persists. Also are you using same account for multiple workers?

**Comment by RobJah** [comment] 2019-03-20 09:38
Thnx, i can test it tonight :)

**Comment by RobJah** [comment] 2019-03-21 19:11
Yo guys,

Been running the new version, but the market is nog really giving it enough action yet to say that the issue is gone. I will report back when the markets move, or sunday, which ever comes first.

peace

**Comment by RobJah** [comment] 2019-03-22 17:07
Guys (n Gals)

Havent seen any errors of gui-freezing so far and the market did move a couple of times in a big enough way that im willing to say this issue is resolved.

Thnx!

**Closed** 2019-03-22 19:49 UTC
